name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  BUILD_LLVM: 'ON'

stages:
    - stage: BuildLLVM13
      jobs:
      - job: BuildLLVM13Linux
        timeoutInMinutes: "0"
        displayName: Linux
        continueOnError: "false"
        pool:
          vmImage: "ubuntu-20.04"
        variables:
          CCACHE_DIR: '$(Pipeline.Workspace)/ccache'
          BUILD_DIRECTORY: '$(System.DefaultWorkingDirectory)/build'
          SOURCE_DIRECTORY: '$(System.DefaultWorkingDirectory)'
          INSTALL_DIRECTORY: '$(System.DefaultWorkingDirectory)/llvm-13-Ubuntu-gcc10-install'
        strategy:
          matrix:
            64-bit Linux Release:
              BuildType: Release
            64-bit Linux Debug:
              BuildType: Debug
        steps:
          - checkout: self
            submodules: recursive
          - script: |
              echo "Build.DefinitionName $(Build.DefinitionName)"
              echo "System.DefinitionId	 $(System.DefinitionId)"
              echo "Agent.OS $(Agent.OS)"
              echo "System.TeamProject $(System.TeamProject)"
              echo "System.TeamProjectId $(System.TeamProjectId)"
              echo "System.AccessToken  $(System.AccessToken)"
              echo "System.CollectionId $(System.CollectionId)"
              echo "System.CollectionUri  $(System.CollectionUri)"
              echo "System.DefaultWorkingDirectory  $(System.DefaultWorkingDirectory)"
              echo "System.DefinitionId $(System.DefinitionId)"
              echo "System.HostType $(System.HostType)"
              echo "System.JobAttempt $(System.JobAttempt)"
              echo "System.JobDisplayName $(System.JobDisplayName)"
              echo "System.JobId  $(System.JobId)"
              echo "System.JobName  $(System.JobName)"
              echo "System.PhaseAttempt $(System.PhaseAttempt)"
              echo "System.PhaseDisplayName $(System.PhaseDisplayName)"
              echo "System.PhaseName  $(System.PhaseName)"
              echo "System.StageAttempt $(System.StageAttempt)"
              echo "System.StageDisplayName $(System.StageDisplayName)"
              echo "System.StageName  $(System.StageName)"
              echo "System.PullRequest.IsFork $(System.PullRequest.IsFork)"
              echo "System.PullRequest.PullRequestId $(System.PullRequest.PullRequestId)"
              echo "System.PullRequest.PullRequestNumber $(System.PullRequest.PullRequestNumber)"
              echo "System.PullRequest.SourceBranch $(System.PullRequest.SourceBranch)"
              echo "System.PullRequest.SourceRepositoryURI $(System.PullRequest.SourceRepositoryURI)"
              echo "System.PullRequest.TargetBranch $(System.PullRequest.TargetBranch)"
              echo "System.TeamFoundationCollectionUri $(System.TeamFoundationCollectionUri)"
              echo "System.TeamProject $(System.TeamProject)"
              echo "System.TeamProjectId $(System.TeamProjectId)"
              echo "TF_BUILD $(TF_BUILD)"
            displayName: Print Variables
          - script: |
              echo "gcc $(gcc --version)"
              echo "g++ $(g++ --version)"
              sudo add-apt-repository ppa:ubuntu-toolchain-r/test
              sudo apt-get update
              sudo apt-get install -y gcc-10 g++-10
              sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 1
              sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 1
              echo "gcc $(gcc --version)"
              echo "g++ $(g++ --version)"
            displayName: Install g++10
          - script: |
              mkdir $(BUILD_DIRECTORY)
              cd $(BUILD_DIRECTORY)
              cmake -DCMAKE_INSTALL_PREFIX="$(INSTALL_DIRECTORY)/$(BuildType)" -DCMAKE_BUILD_TYPE=$(BuildType) ../llvm
            displayName: ConfigureCommand
          - script: |
              cd $(BUILD_DIRECTORY)
              cmake --build . --target install --config $(BuildType) -j 12
            displayName: BuildCommand
          - task: CopyFiles@2
            inputs:
              contents: '$(INSTALL_DIRECTORY)/$(BuildType)/**'
              targetFolder: $(Build.ArtifactStagingDirectory)
          - publish: $(Build.ArtifactStagingDirectory)
            artifact: llvm-13.x-$(Agent.OS)-$(BuildType)

      - job: BuildLLVM13Windows
        timeoutInMinutes: "0"
        displayName: Windows
        continueOnError: "false"
        pool:
          vmImage: "windows-2019"
        variables:
          CCACHE_DIR: '$(Pipeline.Workspace)/ccache'
          SOURCE_DIRECTORY: '$(System.DefaultWorkingDirectory)'
          BUILD_DIRECTORY: '$(SOURCE_DIRECTORY)\build'
          INSTALL_DIRECTORY: '$(SOURCE_DIRECTORY)\llvm-13-win32-mscv2019-install'
        strategy:
          matrix:
            64-bit Windows Release:
              BuildType: Release
            64-bit Windows RelWithDebInfo:
              BuildType: RelWithDebInfo
            #64-bit Windows Debug:
            #  BuildType: Debug
        steps:
          - checkout: self
            submodules: recursive

          - script: |
              echo "Build.DefinitionName $(Build.DefinitionName)"
              echo "System.DefinitionId	 $(System.DefinitionId)"
              echo "Agent.OS $(Agent.OS)"
              echo "System.TeamProject $(System.TeamProject)"
              echo "System.TeamProjectId $(System.TeamProjectId)"
              echo "System.AccessToken  $(System.AccessToken)"
              echo "System.CollectionId $(System.CollectionId)"
              echo "System.CollectionUri  $(System.CollectionUri)"
              echo "System.DefaultWorkingDirectory  $(System.DefaultWorkingDirectory)"
              echo "System.DefinitionId $(System.DefinitionId)"
              echo "System.HostType $(System.HostType)"
              echo "System.JobAttempt $(System.JobAttempt)"
              echo "System.JobDisplayName $(System.JobDisplayName)"
              echo "System.JobId  $(System.JobId)"
              echo "System.JobName  $(System.JobName)"
              echo "System.PhaseAttempt $(System.PhaseAttempt)"
              echo "System.PhaseDisplayName $(System.PhaseDisplayName)"
              echo "System.PhaseName  $(System.PhaseName)"
              echo "System.StageAttempt $(System.StageAttempt)"
              echo "System.StageDisplayName $(System.StageDisplayName)"
              echo "System.StageName  $(System.StageName)"
              echo "System.PullRequest.IsFork $(System.PullRequest.IsFork)"
              echo "System.PullRequest.PullRequestId $(System.PullRequest.PullRequestId)"
              echo "System.PullRequest.PullRequestNumber $(System.PullRequest.PullRequestNumber)"
              echo "System.PullRequest.SourceBranch $(System.PullRequest.SourceBranch)"
              echo "System.PullRequest.SourceRepositoryURI $(System.PullRequest.SourceRepositoryURI)"
              echo "System.PullRequest.TargetBranch $(System.PullRequest.TargetBranch)"
              echo "System.TeamFoundationCollectionUri $(System.TeamFoundationCollectionUri)"
              echo "System.TeamProject $(System.TeamProject)"
              echo "System.TeamProjectId $(System.TeamProjectId)"
              echo "TF_BUILD $(TF_BUILD)"
            displayName: Print Variables
          - powershell: |
              mkdir $(BUILD_DIRECTORY)
              cd $(BUILD_DIRECTORY)
              cmake -DCMAKE_INSTALL_PREFIX="$(INSTALL_DIRECTORY)/$(BuildType)" -DCMAKE_BUILD_TYPE=$(BuildType) ../llvm
            displayName: ConfigureCommand
          - powershell: |
              cd $(BUILD_DIRECTORY)
              cmake --build . --target install --config $(BuildType) -j 12
            displayName: BuildCommand
          - script: |
              cd $(INSTALL_DIRECTORY)/$(BuildType)
              mv bin/llvm-config.exe .
              rm -r bin
              mkdir bin
              mv llvm-config.exe bin
              tree /f
            displayName: RemoveExtraExecutables
          - task: CopyFiles@2
            inputs:
              contents: '$(INSTALL_DIRECTORY)/$(BuildType)/**'
              targetFolder: $(Build.ArtifactStagingDirectory)
          - publish: $(Build.ArtifactStagingDirectory)
            artifact: llvm-13.x-$(Agent.OS)-$(BuildType)

      - job: BuildLLVM13Mac
        timeoutInMinutes: "0"
        displayName: MacOS
        continueOnError: "false"
        pool:
          vmImage: 'macOS-11'
        variables:
          CCACHE_DIR: '$(Pipeline.Workspace)/ccache'
          BUILD_DIRECTORY: '$(System.DefaultWorkingDirectory)/build'
          SOURCE_DIRECTORY: '$(System.DefaultWorkingDirectory)'
          INSTALL_DIRECTORY: '$(System.DefaultWorkingDirectory)/llvm-13-macos10.15-install'
        strategy:
          matrix:
            64-bit Mac Release:
              BuildType: Release
            64-bit Mac Debug:
              BuildType: Debug
        steps:
          - checkout: self
            submodules: recursive
          - script: |
              echo "Build.DefinitionName $(Build.DefinitionName)"
              echo "System.DefinitionId	 $(System.DefinitionId)"
              echo "Agent.OS $(Agent.OS)"
              echo "System.TeamProject $(System.TeamProject)"
              echo "System.TeamProjectId $(System.TeamProjectId)"
              echo "System.AccessToken  $(System.AccessToken)"
              echo "System.CollectionId $(System.CollectionId)"
              echo "System.CollectionUri  $(System.CollectionUri)"
              echo "System.DefaultWorkingDirectory  $(System.DefaultWorkingDirectory)"
              echo "System.DefinitionId $(System.DefinitionId)"
              echo "System.HostType $(System.HostType)"
              echo "System.JobAttempt $(System.JobAttempt)"
              echo "System.JobDisplayName $(System.JobDisplayName)"
              echo "System.JobId  $(System.JobId)"
              echo "System.JobName  $(System.JobName)"
              echo "System.PhaseAttempt $(System.PhaseAttempt)"
              echo "System.PhaseDisplayName $(System.PhaseDisplayName)"
              echo "System.PhaseName  $(System.PhaseName)"
              echo "System.StageAttempt $(System.StageAttempt)"
              echo "System.StageDisplayName $(System.StageDisplayName)"
              echo "System.StageName  $(System.StageName)"
              echo "System.PullRequest.IsFork $(System.PullRequest.IsFork)"
              echo "System.PullRequest.PullRequestId $(System.PullRequest.PullRequestId)"
              echo "System.PullRequest.PullRequestNumber $(System.PullRequest.PullRequestNumber)"
              echo "System.PullRequest.SourceBranch $(System.PullRequest.SourceBranch)"
              echo "System.PullRequest.SourceRepositoryURI $(System.PullRequest.SourceRepositoryURI)"
              echo "System.PullRequest.TargetBranch $(System.PullRequest.TargetBranch)"
              echo "System.TeamFoundationCollectionUri $(System.TeamFoundationCollectionUri)"
              echo "System.TeamProject $(System.TeamProject)"
              echo "System.TeamProjectId $(System.TeamProjectId)"
              echo "TF_BUILD $(TF_BUILD)"
            displayName: Print Variables
          - script: |
              echo "installing tree"
              brew install tree
            displayName: Install tree
            condition: ne(variables.SWIG_CACHE, 'true')
          - script: |
              mkdir $(BUILD_DIRECTORY)
              cd $(BUILD_DIRECTORY)
              cmake -DCMAKE_INSTALL_PREFIX="$(INSTALL_DIRECTORY)/$(BuildType)" -DCMAKE_BUILD_TYPE=$(BuildType)  ../llvm
            displayName: ConfigureCommand
          - script: |
              cd $(BUILD_DIRECTORY)
              cmake --build . --target install --config $(BuildType) -j 12
            displayName: BuildCommand
          - script: |
              cd $(INSTALL_DIRECTORY)/$(BuildType)
              mv bin/llvm-config* .
              rm -r bin
              mkdir bin
              mv llvm-config* bin
              tree /f
            displayName: RemoveExtraExecutables
          - task: CopyFiles@2
            inputs:
              contents: '$(INSTALL_DIRECTORY)/$(BuildType)/**'
              targetFolder: $(Build.ArtifactStagingDirectory)
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: $(Build.ArtifactStagingDirectory)
              artifactName: llvm-13.x-$(Agent.OS)-$(BuildType)
